// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Gear: typeof import('./components/Icons/Gear.vue')['default']
    GithubRepoCard: typeof import('./components/GithubRepoCard.vue')['default']
    GithubRepos: typeof import('./components/GithubRepos.vue')['default']
    README: typeof import('./components/README.md')['default']
  }
}

export { }
